import type { SavedSite } from "@/lib/site-types";

export const localSites: SavedSite[] = [
  {
    id: "site-1",
    title: "Vercel Identicon Prototypes",
    meta: "avatar•generator",
    clicks: 142,
    category: "DESIGN",
    source: "local",
  },
  {
    id: "site-2",
    title: "OpenAI Playground",
    meta: "ai•sandbox",
    clicks: 188,
    category: "RESOURCES",
    source: "local",
  },
  {
    id: "site-3",
    title: "Awwwards",
    meta: "design•inspiration",
    clicks: 66,
    category: "INSPIRATION",
    source: "local",
  },
  {
    id: "site-4",
    title: "Notion Documentation",
    meta: "docs•knowledge",
    clicks: 97,
    category: "KNOWLEDGE",
    source: "local",
  },
  {
    id: "site-5",
    title: "Shadcn/UI Registry",
    meta: "ui•components",
    clicks: 154,
    category: "RESOURCES",
    source: "local",
  },
  {
    id: "site-5b",
    title: "Radix UI Primitives",
    meta: "components•a11y",
    clicks: 128,
    category: "COMPONENTS",
    source: "local",
  },
  {
    id: "site-6",
    title: "Linear Changelog",
    meta: "product•updates",
    clicks: 48,
    category: "PROJECT",
    source: "local",
  },
  {
    id: "site-7",
    title: "Anthropic Console",
    meta: "ai•api",
    clicks: 58,
    category: "RESOURCES",
    source: "local",
  },
  {
    id: "site-8",
    title: "Design Systems Repo",
    meta: "design-system•reference",
    clicks: 45,
    category: "DESIGN",
    source: "local",
  },
  {
    id: "site-9",
    title: "Mobbin UI Patterns",
    meta: "mobile-ui•patterns",
    clicks: 119,
    category: "INSPIRATION",
    source: "local",
  },
  {
    id: "site-10",
    title: "MDN Web Docs",
    meta: "web•docs",
    clicks: 135,
    category: "KNOWLEDGE",
    source: "local",
  },
  {
    id: "site-11",
    title: "React Aria",
    meta: "components•a11y",
    clicks: 87,
    category: "RESOURCES",
    source: "local",
  },
  {
    id: "site-12",
    title: "arcory Internal Board",
    meta: "project•tracking",
    clicks: 36,
    category: "PROJECT",
    source: "local",
  },
];
